### PR TITLE
[MINOR]: Update README.md

### PR DESCRIPTION
**Pull request by avincodes**
Made some minor changes to `readme.md`.  Please don't mark this pull request as hacktoberfest-accepted as it is not worth it! 😄

### CODE REVIEW

**Comment by avincodes** [comment]
@BuddhikaD forgot to tag!

**Comment by avincodes** [comment]
@BuddhikaD please merge this so I can complete the work in this repo! Thanks

**Comment by BuddhikaD** [comment]
Merged

**Comment by avincodes** [comment]
> Merged 

Thanks bro!

**Pull request merged**
